version: 2
updates:
  # NPM updates for astro site
  - package-ecosystem: "npm"
    directory: "/web"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[SECURITY] - Website Dependencies: "

  # pip updates for Python scripts
  - package-ecosystem: "pip"
    directory: "/lib"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "auto"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "[SECURITY] - Python Dependencies: "
